spring:
    datasource:
        password: root
        url: jdbc:mysql://localhost:3306/product_service
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                format_sql: true
        show-sql: true
server:
    error:
        include-message: always
s2s:
    url: http://localhost:8081/car

